FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python3", "-m", "src.main", "--mode", "production", "--config", "configs/docker-rpicam.yaml", "--source", "webcam"]

